In [ ]:
#1- Criar um array de 10 cincos

In [1]:
import numpy as np

In [2]:
x=[5]

In [4]:
np.array(x*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
#2 - Criar um array com todos os inteiros de 10 a 50 inclusive

In [14]:
import numpy as np

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#3 - Criar uma matriz 3x3 com valores variando de 0 a 8

In [7]:
my_matrix = [[0,2,5],[1,3,7],[4,6,8]] 

In [8]:
my_matrix

[[0, 2, 5], [1, 3, 7], [4, 6, 8]]

In [9]:
np.array(my_matrix)

array([[0, 2, 5],
       [1, 3, 7],
       [4, 6, 8]])

In [ ]:
#4-  Criar uma matriz identidade 3 x 3

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#5 - Use Numpy para gerar um array de 25 números aléatórios pertencentes a distibuição normal padronizada

In [5]:
import numpy as np

In [6]:
np.random.randn(25)

array([-2.171003  , -0.61049433,  0.40112096,  0.57157549,  0.37860328,
       -1.77094826, -0.22290802, -0.70123909, -1.37911114, -1.11384131,
        1.12679938,  1.08789555,  0.03241849, -0.51566077, -0.96700822,
        0.20994149,  0.92369931, -0.5835562 , -0.38698178,  0.4723157 ,
        0.36170087,  0.15201442, -0.20919709,  0.54032872, -0.29981834])

In [ ]:
#6 -Crie um código que reproduza a matriz abaixo:

In [ ]:
#7 -  Criar um array com 20 pontos espaçados entre 0 e 1

In [10]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#8 - Crie um código que reproduza o output abaixo:

In [ ]:
#9 - Crie um código que reproduza o output abaixo:

In [ ]:
#10-  Crie um código que reproduza o output abaixo:

In [49]:
my_list = [21,22,23,24,25]

In [50]:
my_list

[21, 22, 23, 24, 25]

In [51]:
np.array(my_list)

array([21, 22, 23, 24, 25])

In [ ]:
#11 - Crie um código que reproduza o output abaixo:

In [52]:
my_matrix = [[16,17,18,19,20],[21,22,23,24,25]] 

In [53]:
my_matrix

[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]

In [54]:
np.array(my_matrix)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])